package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.Concept;

public interface ConceptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    int insert(Concept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concept
     *
     * @mbg.generated
     */
    int insertSelective(Concept record);
}