package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.Emotion;

public interface EmotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion
     *
     * @mbg.generated
     */
    int insert(Emotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emotion
     *
     * @mbg.generated
     */
    int insertSelective(Emotion record);
}