package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.StockStatistics;

public interface StockStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_statistics
     *
     * @mbg.generated
     */
    int insert(StockStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_statistics
     *
     * @mbg.generated
     */
    int insertSelective(StockStatistics record);
}