package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.StockKpl;

public interface StockKplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_kpl
     *
     * @mbg.generated
     */
    int insert(StockKpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_kpl
     *
     * @mbg.generated
     */
    int insertSelective(StockKpl record);
}