package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.TradeDate;

public interface TradeDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    int insert(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    int insertSelective(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    TradeDate selectByPrimaryKey(String date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_date
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeDate record);
}