package com.wujm1.tradesystem.mapper;

import com.wujm1.tradesystem.entity.WencaiCondition;

public interface WencaiConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String conditionName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    int insert(WencaiCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    int insertSelective(WencaiCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    WencaiCondition selectByPrimaryKey(String conditionName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WencaiCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WencaiCondition record);
}