package com.wujm1.tradesystem.entity;

import java.io.Serializable;

public class Concept implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column concept.concept
     *
     * @mbg.generated
     */
    private String concept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table concept
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.code
     *
     * @return the value of concept.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.code
     *
     * @param code the value for concept.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column concept.concept
     *
     * @return the value of concept.concept
     *
     * @mbg.generated
     */
    public String getConcept() {
        return concept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column concept.concept
     *
     * @param concept the value for concept.concept
     *
     * @mbg.generated
     */
    public void setConcept(String concept) {
        this.concept = concept == null ? null : concept.trim();
    }
}