package com.wujm1.tradesystem.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StockKpl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.fde
     *
     * @mbg.generated
     */
    private BigDecimal fde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.max_fed
     *
     * @mbg.generated
     */
    private BigDecimal maxFed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.zlje
     *
     * @mbg.generated
     */
    private BigDecimal zlje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.zlmr
     *
     * @mbg.generated
     */
    private BigDecimal zlmr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.zlmc
     *
     * @mbg.generated
     */
    private BigDecimal zlmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.concept
     *
     * @mbg.generated
     */
    private String concept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.amplitude
     *
     * @mbg.generated
     */
    private BigDecimal amplitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.ceiling_days
     *
     * @mbg.generated
     */
    private Integer ceilingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.free_market
     *
     * @mbg.generated
     */
    private BigDecimal freeMarket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.swap
     *
     * @mbg.generated
     */
    private BigDecimal swap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_kpl.last_ceiling_time
     *
     * @mbg.generated
     */
    private String lastCeilingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_kpl
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.date
     *
     * @return the value of stock_kpl.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.date
     *
     * @param date the value for stock_kpl.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.code
     *
     * @return the value of stock_kpl.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.code
     *
     * @param code the value for stock_kpl.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.name
     *
     * @return the value of stock_kpl.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.name
     *
     * @param name the value for stock_kpl.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.group_name
     *
     * @return the value of stock_kpl.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.group_name
     *
     * @param groupName the value for stock_kpl.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.fde
     *
     * @return the value of stock_kpl.fde
     *
     * @mbg.generated
     */
    public BigDecimal getFde() {
        return fde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.fde
     *
     * @param fde the value for stock_kpl.fde
     *
     * @mbg.generated
     */
    public void setFde(BigDecimal fde) {
        this.fde = fde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.max_fed
     *
     * @return the value of stock_kpl.max_fed
     *
     * @mbg.generated
     */
    public BigDecimal getMaxFed() {
        return maxFed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.max_fed
     *
     * @param maxFed the value for stock_kpl.max_fed
     *
     * @mbg.generated
     */
    public void setMaxFed(BigDecimal maxFed) {
        this.maxFed = maxFed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.zlje
     *
     * @return the value of stock_kpl.zlje
     *
     * @mbg.generated
     */
    public BigDecimal getZlje() {
        return zlje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.zlje
     *
     * @param zlje the value for stock_kpl.zlje
     *
     * @mbg.generated
     */
    public void setZlje(BigDecimal zlje) {
        this.zlje = zlje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.zlmr
     *
     * @return the value of stock_kpl.zlmr
     *
     * @mbg.generated
     */
    public BigDecimal getZlmr() {
        return zlmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.zlmr
     *
     * @param zlmr the value for stock_kpl.zlmr
     *
     * @mbg.generated
     */
    public void setZlmr(BigDecimal zlmr) {
        this.zlmr = zlmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.zlmc
     *
     * @return the value of stock_kpl.zlmc
     *
     * @mbg.generated
     */
    public BigDecimal getZlmc() {
        return zlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.zlmc
     *
     * @param zlmc the value for stock_kpl.zlmc
     *
     * @mbg.generated
     */
    public void setZlmc(BigDecimal zlmc) {
        this.zlmc = zlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.amount
     *
     * @return the value of stock_kpl.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.amount
     *
     * @param amount the value for stock_kpl.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.concept
     *
     * @return the value of stock_kpl.concept
     *
     * @mbg.generated
     */
    public String getConcept() {
        return concept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.concept
     *
     * @param concept the value for stock_kpl.concept
     *
     * @mbg.generated
     */
    public void setConcept(String concept) {
        this.concept = concept == null ? null : concept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.amplitude
     *
     * @return the value of stock_kpl.amplitude
     *
     * @mbg.generated
     */
    public BigDecimal getAmplitude() {
        return amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.amplitude
     *
     * @param amplitude the value for stock_kpl.amplitude
     *
     * @mbg.generated
     */
    public void setAmplitude(BigDecimal amplitude) {
        this.amplitude = amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.ceiling_days
     *
     * @return the value of stock_kpl.ceiling_days
     *
     * @mbg.generated
     */
    public Integer getCeilingDays() {
        return ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.ceiling_days
     *
     * @param ceilingDays the value for stock_kpl.ceiling_days
     *
     * @mbg.generated
     */
    public void setCeilingDays(Integer ceilingDays) {
        this.ceilingDays = ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.free_market
     *
     * @return the value of stock_kpl.free_market
     *
     * @mbg.generated
     */
    public BigDecimal getFreeMarket() {
        return freeMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.free_market
     *
     * @param freeMarket the value for stock_kpl.free_market
     *
     * @mbg.generated
     */
    public void setFreeMarket(BigDecimal freeMarket) {
        this.freeMarket = freeMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.swap
     *
     * @return the value of stock_kpl.swap
     *
     * @mbg.generated
     */
    public BigDecimal getSwap() {
        return swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.swap
     *
     * @param swap the value for stock_kpl.swap
     *
     * @mbg.generated
     */
    public void setSwap(BigDecimal swap) {
        this.swap = swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_kpl.last_ceiling_time
     *
     * @return the value of stock_kpl.last_ceiling_time
     *
     * @mbg.generated
     */
    public String getLastCeilingTime() {
        return lastCeilingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_kpl.last_ceiling_time
     *
     * @param lastCeilingTime the value for stock_kpl.last_ceiling_time
     *
     * @mbg.generated
     */
    public void setLastCeilingTime(String lastCeilingTime) {
        this.lastCeilingTime = lastCeilingTime == null ? null : lastCeilingTime.trim();
    }
}