package com.wujm1.tradesystem.entity;

import java.io.Serializable;

public class StockStatistics implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.ceiling_days
     *
     * @mbg.generated
     */
    private Integer ceilingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.ceiling_type
     *
     * @mbg.generated
     */
    private String ceilingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.ceiling_time
     *
     * @mbg.generated
     */
    private String ceilingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_statistics.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_statistics
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.date
     *
     * @return the value of stock_statistics.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.date
     *
     * @param date the value for stock_statistics.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.code
     *
     * @return the value of stock_statistics.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.code
     *
     * @param code the value for stock_statistics.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.name
     *
     * @return the value of stock_statistics.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.name
     *
     * @param name the value for stock_statistics.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.group_name
     *
     * @return the value of stock_statistics.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.group_name
     *
     * @param groupName the value for stock_statistics.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.ceiling_days
     *
     * @return the value of stock_statistics.ceiling_days
     *
     * @mbg.generated
     */
    public Integer getCeilingDays() {
        return ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.ceiling_days
     *
     * @param ceilingDays the value for stock_statistics.ceiling_days
     *
     * @mbg.generated
     */
    public void setCeilingDays(Integer ceilingDays) {
        this.ceilingDays = ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.ceiling_type
     *
     * @return the value of stock_statistics.ceiling_type
     *
     * @mbg.generated
     */
    public String getCeilingType() {
        return ceilingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.ceiling_type
     *
     * @param ceilingType the value for stock_statistics.ceiling_type
     *
     * @mbg.generated
     */
    public void setCeilingType(String ceilingType) {
        this.ceilingType = ceilingType == null ? null : ceilingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.ceiling_time
     *
     * @return the value of stock_statistics.ceiling_time
     *
     * @mbg.generated
     */
    public String getCeilingTime() {
        return ceilingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.ceiling_time
     *
     * @param ceilingTime the value for stock_statistics.ceiling_time
     *
     * @mbg.generated
     */
    public void setCeilingTime(String ceilingTime) {
        this.ceilingTime = ceilingTime == null ? null : ceilingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_statistics.reason
     *
     * @return the value of stock_statistics.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_statistics.reason
     *
     * @param reason the value for stock_statistics.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}