package com.wujm1.tradesystem.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Stock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.date
     *
     * @mbg.generated
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.open
     *
     * @mbg.generated
     */
    private BigDecimal open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.close
     *
     * @mbg.generated
     */
    private BigDecimal close;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.high
     *
     * @mbg.generated
     */
    private BigDecimal high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.low
     *
     * @mbg.generated
     */
    private BigDecimal low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.r_close
     *
     * @mbg.generated
     */
    private BigDecimal rClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.vol
     *
     * @mbg.generated
     */
    private Long vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.amplitude
     *
     * @mbg.generated
     */
    private BigDecimal amplitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.chg
     *
     * @mbg.generated
     */
    private BigDecimal chg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.swap
     *
     * @mbg.generated
     */
    private BigDecimal swap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.first_ceiling_time
     *
     * @mbg.generated
     */
    private String firstCeilingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.last_ceiling_time
     *
     * @mbg.generated
     */
    private String lastCeilingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.ceiling_open_times
     *
     * @mbg.generated
     */
    private Integer ceilingOpenTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.vol_rate
     *
     * @mbg.generated
     */
    private BigDecimal volRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.fde
     *
     * @mbg.generated
     */
    private BigDecimal fde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.fcb
     *
     * @mbg.generated
     */
    private BigDecimal fcb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.tdzlje
     *
     * @mbg.generated
     */
    private BigDecimal tdzlje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.call_vol
     *
     * @mbg.generated
     */
    private BigDecimal callVol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.ceiling_type
     *
     * @mbg.generated
     */
    private String ceilingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.free_market
     *
     * @mbg.generated
     */
    private BigDecimal freeMarket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.ceiling_days
     *
     * @mbg.generated
     */
    private Integer ceilingDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.call_vol_rate
     *
     * @mbg.generated
     */
    private BigDecimal callVolRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.last_date
     *
     * @mbg.generated
     */
    private String lastDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.call_amount
     *
     * @mbg.generated
     */
    private BigDecimal callAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.ceiling_struct
     *
     * @mbg.generated
     */
    private String ceilingStruct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.k_type
     *
     * @mbg.generated
     */
    private String kType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.concepts
     *
     * @mbg.generated
     */
    private String concepts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.date
     *
     * @return the value of stock.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.date
     *
     * @param date the value for stock.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.code
     *
     * @return the value of stock.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.code
     *
     * @param code the value for stock.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.open
     *
     * @return the value of stock.open
     *
     * @mbg.generated
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.open
     *
     * @param open the value for stock.open
     *
     * @mbg.generated
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.close
     *
     * @return the value of stock.close
     *
     * @mbg.generated
     */
    public BigDecimal getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.close
     *
     * @param close the value for stock.close
     *
     * @mbg.generated
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.high
     *
     * @return the value of stock.high
     *
     * @mbg.generated
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.high
     *
     * @param high the value for stock.high
     *
     * @mbg.generated
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.low
     *
     * @return the value of stock.low
     *
     * @mbg.generated
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.low
     *
     * @param low the value for stock.low
     *
     * @mbg.generated
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.r_close
     *
     * @return the value of stock.r_close
     *
     * @mbg.generated
     */
    public BigDecimal getrClose() {
        return rClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.r_close
     *
     * @param rClose the value for stock.r_close
     *
     * @mbg.generated
     */
    public void setrClose(BigDecimal rClose) {
        this.rClose = rClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.amount
     *
     * @return the value of stock.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.amount
     *
     * @param amount the value for stock.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.vol
     *
     * @return the value of stock.vol
     *
     * @mbg.generated
     */
    public Long getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.vol
     *
     * @param vol the value for stock.vol
     *
     * @mbg.generated
     */
    public void setVol(Long vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.amplitude
     *
     * @return the value of stock.amplitude
     *
     * @mbg.generated
     */
    public BigDecimal getAmplitude() {
        return amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.amplitude
     *
     * @param amplitude the value for stock.amplitude
     *
     * @mbg.generated
     */
    public void setAmplitude(BigDecimal amplitude) {
        this.amplitude = amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.chg
     *
     * @return the value of stock.chg
     *
     * @mbg.generated
     */
    public BigDecimal getChg() {
        return chg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.chg
     *
     * @param chg the value for stock.chg
     *
     * @mbg.generated
     */
    public void setChg(BigDecimal chg) {
        this.chg = chg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.swap
     *
     * @return the value of stock.swap
     *
     * @mbg.generated
     */
    public BigDecimal getSwap() {
        return swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.swap
     *
     * @param swap the value for stock.swap
     *
     * @mbg.generated
     */
    public void setSwap(BigDecimal swap) {
        this.swap = swap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.reason
     *
     * @return the value of stock.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.reason
     *
     * @param reason the value for stock.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.first_ceiling_time
     *
     * @return the value of stock.first_ceiling_time
     *
     * @mbg.generated
     */
    public String getFirstCeilingTime() {
        return firstCeilingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.first_ceiling_time
     *
     * @param firstCeilingTime the value for stock.first_ceiling_time
     *
     * @mbg.generated
     */
    public void setFirstCeilingTime(String firstCeilingTime) {
        this.firstCeilingTime = firstCeilingTime == null ? null : firstCeilingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.last_ceiling_time
     *
     * @return the value of stock.last_ceiling_time
     *
     * @mbg.generated
     */
    public String getLastCeilingTime() {
        return lastCeilingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.last_ceiling_time
     *
     * @param lastCeilingTime the value for stock.last_ceiling_time
     *
     * @mbg.generated
     */
    public void setLastCeilingTime(String lastCeilingTime) {
        this.lastCeilingTime = lastCeilingTime == null ? null : lastCeilingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.ceiling_open_times
     *
     * @return the value of stock.ceiling_open_times
     *
     * @mbg.generated
     */
    public Integer getCeilingOpenTimes() {
        return ceilingOpenTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.ceiling_open_times
     *
     * @param ceilingOpenTimes the value for stock.ceiling_open_times
     *
     * @mbg.generated
     */
    public void setCeilingOpenTimes(Integer ceilingOpenTimes) {
        this.ceilingOpenTimes = ceilingOpenTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.vol_rate
     *
     * @return the value of stock.vol_rate
     *
     * @mbg.generated
     */
    public BigDecimal getVolRate() {
        return volRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.vol_rate
     *
     * @param volRate the value for stock.vol_rate
     *
     * @mbg.generated
     */
    public void setVolRate(BigDecimal volRate) {
        this.volRate = volRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.fde
     *
     * @return the value of stock.fde
     *
     * @mbg.generated
     */
    public BigDecimal getFde() {
        return fde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.fde
     *
     * @param fde the value for stock.fde
     *
     * @mbg.generated
     */
    public void setFde(BigDecimal fde) {
        this.fde = fde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.fcb
     *
     * @return the value of stock.fcb
     *
     * @mbg.generated
     */
    public BigDecimal getFcb() {
        return fcb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.fcb
     *
     * @param fcb the value for stock.fcb
     *
     * @mbg.generated
     */
    public void setFcb(BigDecimal fcb) {
        this.fcb = fcb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.tdzlje
     *
     * @return the value of stock.tdzlje
     *
     * @mbg.generated
     */
    public BigDecimal getTdzlje() {
        return tdzlje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.tdzlje
     *
     * @param tdzlje the value for stock.tdzlje
     *
     * @mbg.generated
     */
    public void setTdzlje(BigDecimal tdzlje) {
        this.tdzlje = tdzlje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.call_vol
     *
     * @return the value of stock.call_vol
     *
     * @mbg.generated
     */
    public BigDecimal getCallVol() {
        return callVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.call_vol
     *
     * @param callVol the value for stock.call_vol
     *
     * @mbg.generated
     */
    public void setCallVol(BigDecimal callVol) {
        this.callVol = callVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.ceiling_type
     *
     * @return the value of stock.ceiling_type
     *
     * @mbg.generated
     */
    public String getCeilingType() {
        return ceilingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.ceiling_type
     *
     * @param ceilingType the value for stock.ceiling_type
     *
     * @mbg.generated
     */
    public void setCeilingType(String ceilingType) {
        this.ceilingType = ceilingType == null ? null : ceilingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.free_market
     *
     * @return the value of stock.free_market
     *
     * @mbg.generated
     */
    public BigDecimal getFreeMarket() {
        return freeMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.free_market
     *
     * @param freeMarket the value for stock.free_market
     *
     * @mbg.generated
     */
    public void setFreeMarket(BigDecimal freeMarket) {
        this.freeMarket = freeMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.ceiling_days
     *
     * @return the value of stock.ceiling_days
     *
     * @mbg.generated
     */
    public Integer getCeilingDays() {
        return ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.ceiling_days
     *
     * @param ceilingDays the value for stock.ceiling_days
     *
     * @mbg.generated
     */
    public void setCeilingDays(Integer ceilingDays) {
        this.ceilingDays = ceilingDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.call_vol_rate
     *
     * @return the value of stock.call_vol_rate
     *
     * @mbg.generated
     */
    public BigDecimal getCallVolRate() {
        return callVolRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.call_vol_rate
     *
     * @param callVolRate the value for stock.call_vol_rate
     *
     * @mbg.generated
     */
    public void setCallVolRate(BigDecimal callVolRate) {
        this.callVolRate = callVolRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.last_date
     *
     * @return the value of stock.last_date
     *
     * @mbg.generated
     */
    public String getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.last_date
     *
     * @param lastDate the value for stock.last_date
     *
     * @mbg.generated
     */
    public void setLastDate(String lastDate) {
        this.lastDate = lastDate == null ? null : lastDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.call_amount
     *
     * @return the value of stock.call_amount
     *
     * @mbg.generated
     */
    public BigDecimal getCallAmount() {
        return callAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.call_amount
     *
     * @param callAmount the value for stock.call_amount
     *
     * @mbg.generated
     */
    public void setCallAmount(BigDecimal callAmount) {
        this.callAmount = callAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.remark
     *
     * @return the value of stock.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.remark
     *
     * @param remark the value for stock.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.ceiling_struct
     *
     * @return the value of stock.ceiling_struct
     *
     * @mbg.generated
     */
    public String getCeilingStruct() {
        return ceilingStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.ceiling_struct
     *
     * @param ceilingStruct the value for stock.ceiling_struct
     *
     * @mbg.generated
     */
    public void setCeilingStruct(String ceilingStruct) {
        this.ceilingStruct = ceilingStruct == null ? null : ceilingStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.k_type
     *
     * @return the value of stock.k_type
     *
     * @mbg.generated
     */
    public String getkType() {
        return kType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.k_type
     *
     * @param kType the value for stock.k_type
     *
     * @mbg.generated
     */
    public void setkType(String kType) {
        this.kType = kType == null ? null : kType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.concepts
     *
     * @return the value of stock.concepts
     *
     * @mbg.generated
     */
    public String getConcepts() {
        return concepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.concepts
     *
     * @param concepts the value for stock.concepts
     *
     * @mbg.generated
     */
    public void setConcepts(String concepts) {
        this.concepts = concepts == null ? null : concepts.trim();
    }
}