package com.wujm1.tradesystem.entity;

import java.io.Serializable;

public class WencaiCondition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wencai_condition.condition_name
     *
     * @mbg.generated
     */
    private String conditionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wencai_condition.condition
     *
     * @mbg.generated
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wencai_condition.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wencai_condition
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wencai_condition.condition_name
     *
     * @return the value of wencai_condition.condition_name
     *
     * @mbg.generated
     */
    public String getConditionName() {
        return conditionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wencai_condition.condition_name
     *
     * @param conditionName the value for wencai_condition.condition_name
     *
     * @mbg.generated
     */
    public void setConditionName(String conditionName) {
        this.conditionName = conditionName == null ? null : conditionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wencai_condition.condition
     *
     * @return the value of wencai_condition.condition
     *
     * @mbg.generated
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wencai_condition.condition
     *
     * @param condition the value for wencai_condition.condition
     *
     * @mbg.generated
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wencai_condition.remark
     *
     * @return the value of wencai_condition.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wencai_condition.remark
     *
     * @param remark the value for wencai_condition.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}